apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: Flask
spec:
  containers:
    - name: myapp-container
      image: obieh/cicdwithgithubactions:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
      